### ISSUE TITLE
Is the LCC global API documented?

### ISSUE THREAD

**Issue by afawcett** [developerforce/LightningContainerExamples#2]
@dougdew Will the LCC global API be documented? I see this repo is referenced in the formal docs for Container Component, but i don't see any reference to the rather handy LCC global API? ;-)

**Comment by dougdew** [comment]
@afawcett Yes, the global API will be documented. And enhanced. There is *very* little functionality in that api now. We are going to add more.

Safe Harbor applies to my statements about future functionality.

Having said that, for Winter 18 we are replacing our use of post-message with channels. The API is higher level and so should not be impacted by the plumbing change underneath.

For future releases, we are hoping to bring features to the LCC API from other iframe environment APIs such as the one provided by Canvas. We would like to unify the iframe environments of features such as LCC and Canvas so that investments in one environment might apply to another environment.

**Comment by afawcett** [comment]
Thanks, thats good to know! This weekend i create a Streaming API component [here](https://github.com/afawcett/streamingcomponent). However i am getting this certificate error in prerel (gs0), is this expected? I get it on all LCC's....

<img width="586" alt="screen shot 2017-05-07 at 22 57 18" src="https://cloud.githubusercontent.com/assets/1167760/25792007/d8897aa2-3378-11e7-9b08-e7496e78c058.png">

**Comment by dougdew** [comment]
We implemented a new DNS domain (container.lightning.com) to use when servicing LCC requests. You should not receive that certificate error. However, we are still updating certificates. We will investigate and fix this problem.

Also, I recommend that you use Chrome instead of Safari for now. For iframe content, Safari detects "too many redirects" by simply detecting circular redirects. So, when attempting the first load of iframe content and having to establish an LCC session, Safari will fail to load the content and complain of too many redirects. We will be fixing that problem in Winter 18. 

Thank you for your patience. And thank you for experimenting with LCC.

**Comment by afawcett** [comment]
Thanks @dougdew. I am actually using Chrome, just that the error dialog is a bit more informative in Safari, so i repo'd it in that. Good to know its something in hand and i'm not doing anything wrong. And thank you for doing such a great job with the examples! 👍

**Comment by dougdew** [comment]
I confirmed with our network engineers that this problem will be solved later this week or early next week.

**Comment by afawcett** [comment]
Thanks @dougdew. One last q, and i'll stop hijacking this issue.... ;-) Is the abstraction behind the LCC also designed to provide a localhost development environment by injecting a session id for local development of the React app without having to run it up in LEX all the time?

**Comment by dougdew** [comment]
Our goal is to enable localhost development. Unfortunately, we probably won't make progress on that goal in Winter 18. Our hope is to invest in the LCC developer experience in Spring 18.

We have considered enabling the use of a local web server that would serve the UI locally and would proxy api calls to force.com. Our goal is to enable rapid UI development iterations with an IDE such as Visual Studio Code, with already-existing build tools such as Webpack and without requiring deployments of a static resource to force.com for each UI iteration. In other words, a ReactJS or AngularJS developer should feel at home building an LCC.

As much as possible, we are hoping to build upon or simply use already-existing tools. The recent news that Webpack will permit add-ons and configurable scaffolding seems very interesting. With that sort of thing, it seems that we could enable a Webpack user to scaffold an LCC conveniently and easily, and use the server provided by Webpack. We will need to investigate to determine if all of that will be possible.

We would welcome and be very appreciative of any ideas, suggestions or requirements that you would provide.

Here's that Webpack news: https://medium.com/webpack/announcing-the-new-webpack-cli-75ce1d9b8663

**Comment by dougdew** [comment]
With regard to not having to "run it up in LEX all the time" it's worth noting that LCC is merely two things:

1. A custom LC
2. A static resource

The static resource can be used without LEX, the same as has always been true of static resources. In other words, it would be possible to access the static resource with a url that begins with "/lcc" directly from the web browser address bar or with a url that begins with "/resource" directly from the browser address bar. Accessing with "/lcc" will cause our LCC servlet to run and to inject the javascript for the LCC environment into the requested *.html page. Requesting with "/resource" will use the older servlet that will merely fetch the requested *.html page without any sort of injection.

For LCC, we are mostly trying to formalize and make convenient what has already become common practice among developers who have been using empty VF pages with third party javascript frameworks.

**Comment by afawcett** [comment]
Thanks @dougdew understood! 👍
