### ISSUE TITLE
Streaming API broken with new CSP connect-src 'self';

### ISSUE THREAD

**Issue by afawcett** [developerforce/LightningContainerExamples#4]
It seems in the latest Summer 17 pre-release, connect-src- 'self' is being added to the CSP header for LCC content. This breaks use of the Streaming API because although the URL domain matches, the protocol wss:/ / does not. Hence you get this error...

~~~~
Refused to connect to 'wss://dlrsprerel-dev-ed--c.container.lightning.com/cometd/39.0' because it violates the following Content Security Policy directive: "connect-src 'self'".
~~~~

You can read more here... https://outlandish.com/blog/configure-content-security-policy-with-websockets-and-express/ and here https://github.com/w3c/webappsec-csp/issues/7

cc @dougdew

**Comment by dougdew** [comment]
@afawcett Thank you very much for the helpful message.

Our intention is that the content within the LCC iframe be API-enabled. Roughly speaking, the content within the LCC iframe should be as enabled as content within a VF page.

We're still working through some details of enabling API access.

**Comment by afawcett** [comment]
Thanks @dougdew for the quick response. I'm really trying hard, for various reasons to get the Streaming API working Lightning. This solution, https://github.com/mshanemc/liveRecord/issues/1, uses the Session ID return from an Apex Aura Enabled method, i was surprised to find this API is API enabled (despite the current docs saying its not supported). Can you shed any light on this more direct route to streaming fun staying or going?

**Comment by dougdew** [comment]
@afawcett The docs explain the restrictions for lightning content. In other words, the stuff that is outside the LCC iframe. The content inside the LCC iframe is served from a different domain than the lightning content outside the LCC iframe and is assigned a different session.

For LCC, we have settled upon a CSP model in which the LCC developer will be able to specify in the LCC's static resource's manifest.json file one of three CSP types: "low", "high" and "custom." 

The "low" CSP type would map roughly to the level of protection currently provided by Visualforce. The "high" CSP type would map to the level of protection provided by lightning. For each of these two CSP types, Salesforce's server would automatically provide the CSP header.

The "custom" CSP type would enable the LCC developer to declare the CSP header that they want. For example, the "custom" CSP type would enable the LCC developer to declare that they want to get javascript from a CDN. A hoped-for benefit of the "custom" CSP type is that AppExchange reviews will be simplified/accelerated due to there being a simple declaration of security needs/intentions.

Having said all of that, we're trying to maintain a tight/limited feature focus for LCC for Winter 18 and so added the connect-src 'self' specification and also script-src 'self' 'unsafe-inline' 'unsafe-eval' specification to the "custom" CSP header. In other words, even if the LCC developer specifies connect-src or script-src in their "custom" CSP, we override their specifications.

We're fully intending to improve upon that in a future release. However, it is likely that we will improve upon that only after we've also implemented a scheme for assigning random domains and sessions to iframed content that has declared with "custom" CSP that it wants to access something like a CDN.

Enabling the ws:// protocol for LCC is probably something that we're going to have to automatically do at the server, given that our server knows the domain being used to serve the iframed LCC content and the domain that should be used to service websocket calls.

I'd like to discuss your need for ws:// support. I'm on vacation this week, but will do my best to keep this conversation going.

**Comment by afawcett** [comment]
Thanks @dougdew, i figured as much tbh, makes sense. 👍

**Comment by dougdew** [comment]
@afawcett Would you please send to me a simplified version of your LCC so that I can make changes and test to ensure that your use of the streaming api will work?

**Comment by afawcett** [comment]
Sure, you should be able to deploy this https://github.com/afawcett/streamingcomponent, via the Deploy to Salesforce button, then follow the setup and demo notes in the README. Thanks for looking into this! 👍

**Comment by afawcett** [comment]
P.S. It would also be good to understand if this more direct solution is working as expected https://github.com/mshanemc/liveRecord/issues/1? Is by design that the Lighting Session ID is API enabled? So far as Streaming API at least it seems?

**Comment by dougdew** [comment]
Thanks!

I'll take a look.

**Comment by afawcett** [comment]
@dougdew Any updates? Should i switch to using the Session API and cometd via ltng:require?

**Comment by dougdew** [comment]
I added support for wss:// to our Winter '18 build last week. It is in testing now.

We'll have to make a decision about backporting to Summer '17.

**Comment by afawcett** [comment]
Ok, thanks, great news! 👍 Regarding Summer'17, i would say it eliminates probably the last reason why one would have to use a VF page or potentially inappropriate use of Aura Session Id if it goes in, thus would encourage considering any change that avoids these a good one priority wise.

**Comment by dougdew** [comment]
By the way, here is a screen shot of your code (with a slight UI change) running on Winter '18:

![image](https://user-images.githubusercontent.com/1242618/27257337-873897d8-5398-11e7-8f09-8ab7f4d139dd.png)

**Comment by afawcett** [comment]
Yay thanks @dougdew! 👍

**Comment by afawcett** [comment]
Oh and btw, do you mind sharing the UI change code you made?

**Comment by dougdew** [comment]
@afawcett Hello. Sorry for the slow reply. I was traveling last week (London) and this week (Seattle) and am catching up a bit now.

I'll share the code just as soon as I get a chance. Would it be ok with you if I shared the code by adding it to this git repo? The code is derived from your code (only minor changes) so it seems to me that I should ask your permission first.

**Comment by afawcett** [comment]
@dougdew totally fine, thank you! 👍

**Comment by pozil** [comment]
Hi @afawcett and @dougdew, I am also looking for WSS support.
Do you have any update to share?

**Comment by afawcett** [comment]
Sadly just tried my code in Winter'18 pre-release and still no joy..

![image](https://user-images.githubusercontent.com/1167760/29497175-0c999d88-8598-11e7-887e-519da8207c3c.png)

**Comment by pozil** [comment]
Yeah, I tried that as well and that is exactly why I joined this discussion :)

**Comment by dougdew** [comment]
@afawcett @pozil After receiving those error messages for an attempted use of GET, did you find that you handshake completed using POST?

**Comment by pozil** [comment]
@dougdew I don't get the same error than @afawcett because we were not using the same code.
I am using CometD to handle to subscription and I see that he just updated his repo to do the same thing now.

@afawcett correct me if I am wrong but the error message we will both have now is this:
```
Refused to connect to 'wss://pozil-dev-ed.lightning.force.com/cometd/40.0/' because it violates the following Content Security Policy directive: "connect-src 'self' *.gus.visual.force.com https://api.bluetail.salesforce.com https://preprod.bluetail.salesforce.com https://gs0.salesforce.com https://staging.bluetail.salesforce.com".
```

The cause of the problem is still what Andrew suggested when opening this issue: CSP won't recognize our domain with the wss protocol.

**Comment by dougdew** [comment]
@pozil The error that @afawcett originally reported happened in Summer '17 code. For that code, the CSP response header did not include support for wss://. The Winter '18 code returns a CSP response header that does include support for wss://.

**Comment by pozil** [comment]
OK, I guess that I trying in the wrong Winter '18 build (org 00DB0000000CXEp on GS0) because I am still experiencing the issue:

![screen shot 2017-08-22 at 14 52 33](https://user-images.githubusercontent.com/5071767/29566490-4dd6b804-874a-11e7-96ed-96e014841cce.png)

Attempt to connect via WSS fails and then CometD rolls back to HTTP transport.

**Comment by dougdew** [comment]
@pozil What is the value of the connect-src portion of the CSP response header that was returned to you?

**Comment by pozil** [comment]
@dougdew here it is:
`
connect-src 'self' https://api.bluetail.salesforce.com https://staging.bluetail.salesforce.com https://preprod.bluetail.salesforce.com *.gus.visual.force.com;`

FYI I noticed that there is a POST to https://th-cat2-dev-ed.lightning.force.com/_/csp happening after to report the blocked WSS call:

Payload:
`{"csp-report":{"document-uri":"https://th-cat2-dev-ed.lightning.force.com/c/testApp.app","referrer":"https://th-cat2-dev-ed.my.salesforce.com/","violated-directive":"connect-src","effective-directive":"connect-src","original-policy":"default-src 'self'; script-src 'self' 'nonce-6e62c57a-8037-b3ff-ad3c-86ebcfc0ba55' chrome-extension: 'unsafe-inline' 'unsafe-eval' https://sfdc.azureedge.net *.gus.visual.force.com https://ssl.gstatic.com/accessibility/; object-src 'self' https://th-cat2-dev-ed--c.gus.content.force.com; style-src 'self' chrome-extension: 'unsafe-inline' *.gus.visual.force.com; img-src 'self' http: https: data: blob: *.gus.visual.force.com; media-src 'self' *.gus.visual.force.com https://th-cat2-dev-ed--c.gus.content.force.com; frame-ancestors 'self'; frame-src https: mailto: *.gus.visual.force.com; font-src 'self' https: data: *.gus.visual.force.com; connect-src 'self' https://api.bluetail.salesforce.com https://staging.bluetail.salesforce.com https://preprod.bluetail.salesforce.com *.gus.visual.force.com; report-uri /_/csp","disposition":"enforce","blocked-uri":"wss://th-cat2-dev-ed.lightning.force.com","line-number":887,"column-number":86,"status-code":0,"script-sample":""}}`



Did I miss something?
Thanks for your patience.

**Comment by dougdew** [comment]
@pozil I will turn this around and say "thank *you* for your patience." Our code should be working correctly, and you are patiently trying to use it, despite the malfunction.

Your connect-src should include a host that begins with "wss://".  I will investigate.

**Comment by dougdew** [comment]
@afawcett @pozil I'm investigating now. 

Did either of you include a manifest.json file in your static resource bundle? If so, what did you specify in your manifest.json file? Most importantly, what did you specify for content-security-policy-type?

**Comment by pozil** [comment]
@dougdew I am not running this in a `lightning:container` so I did not include a manifest.json file.
Should I?

**Comment by afawcett** [comment]
@dougdew i have since moved away from using LCC for this, since that streaming endpoint now appears to be tolerated by regular lc's. Though i must admit the option of using wss (still not supported by lex) over polling http would be nice. Do you still need help here?
